#To create a cluster, run command: k3d cluster create --config <path-to-file>
kind: Simple
apiVersion: k3d.io/v1alpha2
name: small-cluster
image: rancher/k3s:v1.20.4-k3s1
servers: 1
agents: 1
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
options:
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
